export default function PreviewGallery() {
  const designs = [
    { id: 1, name: "Sky Blue Clean", description: "Clean blue design with prominent hero image", colors: ["#0369A1", "#E0F2FE", "#FFFFFF"], preview: "/design1" },
    { id: 2, name: "Minimalist Slate", description: "Professional slate design with hero focus", colors: ["#334155", "#F8FAFC", "#FFFFFF"], preview: "/design2" },
    { id: 3, name: "Irish Flag Premium", description: "Green, white, and orange with hero image", colors: ["#169B62", "#FFFFFF", "#FF883E"], preview: "/design3" },
    { id: 4, name: "Warm Orange", description: "Friendly orange design with hero image", colors: ["#EA580C", "#FFF7ED", "#FFFFFF"], preview: "/design4" },
    { id: 5, name: "Professional Orange", description: "Orange accent with hero image focus", colors: ["#FF883E", "#FFFFFF", "#F7FAFC"], preview: "/design5" },
    { id: 6, name: "Fresh Green", description: "Clean green design with hero image", colors: ["#059669", "#ECFDF5", "#FFFFFF"], preview: "/design6" },
    { id: 7, name: "Golden Amber", description: "Warm amber design with hero image", colors: ["#D97706", "#FEF3C7", "#FFFFFF"], preview: "/design7" },
    { id: 8, name: "Teal Modern", description: "Modern teal design with hero image", colors: ["#0891B2", "#ECFEFF", "#FFFFFF"], preview: "/design8" },
    { id: 9, name: "Rose Pink", description: "Elegant rose design with hero image", colors: ["#E11D48", "#FFF1F2", "#FFFFFF"], preview: "/design9" },
    { id: 10, name: "Professional Gray", description: "Clean gray design with hero image", colors: ["#475569", "#F1F5F9", "#FFFFFF"], preview: "/design10" }
  ];
  return <div style={{minHeight:'100vh',background:'linear-gradient(to bottom, #F9FAFB, #F3F4F6)',padding:'2rem'}}><div style={{maxWidth:'1400px',margin:'0 auto'}}><div style={{textAlign:'center',marginBottom:'3rem'}}><h1 style={{fontSize:'3rem',fontWeight:'800',background:'linear-gradient(135deg, #8B5CF6, #EC4899)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',marginBottom:'1rem'}}>Choose Your Design</h1><p style={{fontSize:'1.25rem',color:'#6B7280',maxWidth:'600px',margin:'0 auto'}}>Select from 10 modern homepage designs with hero images.</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(350px, 1fr))',gap:'2rem',marginBottom:'3rem'}}>{designs.map(d=><div key={d.id} onClick={()=>window.location.href=d.preview} style={{background:'white',borderRadius:'16px',padding:'2rem',boxShadow:'0 4px 12px rgba(0,0,0,0.08)',cursor:'pointer'}}><div style={{display:'inline-block',background:'linear-gradient(135deg, #8B5CF6, #EC4899)',color:'white',fontSize:'0.875rem',fontWeight:'600',padding:'0.25rem 0.75rem',borderRadius:'50px',marginBottom:'0.75rem'}}>Design {d.id}</div><h3 style={{fontSize:'1.5rem',fontWeight:'700',color:'#111827',marginBottom:'0.5rem'}}>{d.name}</h3><p style={{color:'#6B7280',fontSize:'0.95rem',lineHeight:'1.6',marginBottom:'1rem'}}>{d.description}</p><div style={{display:'flex',gap:'0.5rem',marginBottom:'1.5rem'}}>{d.colors.map((c,i)=><div key={i} style={{width:'40px',height:'40px',borderRadius:'50%',border:'3px solid white',boxShadow:'0 2px 8px rgba(0,0,0,0.1)',background:c}}/>)}</div><button style={{width:'100%',padding:'0.875rem',background:'linear-gradient(135deg, #8B5CF6, #EC4899)',color:'white',border:'none',borderRadius:'12px',fontSize:'1rem',fontWeight:'600',cursor:'pointer'}}>Preview Design </button></div>)}</div></div></div>;
}
